const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);
const stamp=()=>new Date().toLocaleString('zh-CN',{hour12:false});
const STORE='ship-tag-prototype-v1';
const seed=()=>({
 version:1,ship:{name:'海澜 01',code:'HL-001'},
 dirs:[{id:'d1',name:'动力区域',parent:'root'},{id:'d2',name:'主机舱',parent:'d1'},{id:'d3',name:'燃油供给部位',parent:'d2'},{id:'d4',name:'冷却部位',parent:'d2'},{id:'d5',name:'辅助机舱',parent:'d1'},{id:'d6',name:'甲板区域',parent:'root'},{id:'d7',name:'艏部甲板',parent:'d6'},{id:'d8',name:'锚泊部位',parent:'d7'},{id:'d9',name:'生活区域',parent:'root'},{id:'d10',name:'配电间',parent:'d9'}],
 assets:[
 {id:'a1',code:'FO-001',name:'燃油输送泵 A',model:'CB-B40',dir:'d3',team:'轮机一组',owner:'张工'},
 {id:'a2',code:'FO-002',name:'燃油输送泵 B',model:'CB-B40',dir:'d3',team:'轮机一组',owner:'张工'},
 {id:'a3',code:'CW-001',name:'海水冷却泵',model:'ISW80',dir:'d4',team:'轮机二组',owner:'李工'},
 {id:'a4',code:'CW-002',name:'板式冷却器',model:'BR0.5',dir:'d4',team:'轮机二组',owner:'李工'},
 {id:'a5',code:'DG-001',name:'辅助发电机',model:'CCFJ120',dir:'d5',team:'电气组',owner:'陈工'},
 {id:'a6',code:'AN-001',name:'左锚机',model:'YM-32',dir:'d8',team:'甲板组',owner:'王工'},
 {id:'a7',code:'AN-002',name:'右锚机',model:'YM-32',dir:'d8',team:'甲板组',owner:'王工'},
 {id:'a8',code:'EL-001',name:'主配电柜',model:'MNS',dir:'d10',team:'电气组',owner:'陈工'}],
 labels:[
 {id:'l1',mac:'C8:29:01:00:00:01',asset:'a1',online:true,battery:86,rssi:-56,template:'t1',version:1,published:1,gateway:'g1',last:'2026-09-14 09:40:02',state:'active'},
 {id:'l2',mac:'C8:29:01:00:00:02',asset:'a2',online:true,battery:72,rssi:-64,template:'t1',version:2,published:1,gateway:'g1',last:'2026-09-14 09:40:05',state:'active'},
 {id:'l3',mac:'C8:29:01:00:00:03',asset:'a3',online:false,battery:55,rssi:-89,template:'t1',version:2,published:1,gateway:'g1',last:'2026-09-13 17:12:40',state:'active'},
 {id:'l4',mac:'C8:29:01:00:00:04',asset:'a4',online:true,battery:12,rssi:-67,template:'t1',version:1,published:1,gateway:'g1',last:'2026-09-14 09:39:51',state:'active'},
 {id:'l5',mac:'C8:29:01:00:00:05',asset:'a5',online:true,battery:92,rssi:-60,template:'t2',version:1,published:1,gateway:'g2',last:'2026-09-14 09:40:10',state:'active'},
 {id:'l6',mac:'C8:29:01:00:00:06',asset:'a6',online:true,battery:65,rssi:-85,template:'t1',version:1,published:1,gateway:'g3',last:'2026-09-14 09:38:16',state:'active'},
 {id:'l7',mac:'C8:29:01:00:00:07',asset:'a7',online:true,battery:78,rssi:-63,template:'t1',version:1,published:1,gateway:'g3',last:'2026-09-14 09:40:12',state:'active'},
 {id:'l8',mac:'C8:29:01:00:00:08',asset:null,online:true,battery:100,rssi:-50,template:'t1',version:1,published:0,gateway:'g2',last:'2026-09-14 09:39:20',state:'active'},
 {id:'l9',mac:'C8:29:01:00:00:09',asset:null,online:false,battery:98,rssi:-74,template:'t1',version:1,published:0,gateway:'g2',last:'2026-09-12 10:21:08',state:'paused'}],
 groups:[{id:'gr1',name:'轮机一组',description:'跨部位维护燃油相关标签',members:['l1','l2']},{id:'gr2',name:'甲板设备',description:'集中管理锚泊部位标签',members:['l6','l7']}],
 fields:[{id:'code',name:'设备编码',type:'文本',required:true},{id:'name',name:'设备名称',type:'文本',required:true},{id:'model',name:'设备型号',type:'文本',required:false},{id:'dir',name:'所属部位',type:'目录',required:true},{id:'team',name:'责任班组',type:'文本',required:false},{id:'owner',name:'责任人',type:'文本',required:false}],
 templates:[{id:'t1',name:'通用设备标签',heading:'设备资产',color:'#202020',showModel:true,showOwner:true,revision:1},{id:'t2',name:'电气设备标签',heading:'电气设备',color:'#ae2424',showModel:true,showOwner:true,revision:1}],
 tasks:[{id:'job-demo',name:'冷却部位标签更新',time:'2026-09-14 09:20:00',items:[{label:'l3',version:2,status:'failed'}]}],
 strategies:[{id:'r1',name:'电气组专用模板',field:'team',value:'电气组',template:'t2',priority:1,enabled:true,scope:'all',schedule:'即时'},{id:'r2',name:'通用默认模板',field:'all',value:'',template:'t1',priority:99,enabled:true,scope:'all',schedule:'即时'}],
 gateways:[{id:'g1',name:'主机舱网关',dir:'d2',online:true,ip:'192.168.10.21'},{id:'g2',name:'辅机舱网关',dir:'d5',online:true,ip:'192.168.10.22'},{id:'g3',name:'艏部网关',dir:'d7',online:true,ip:'192.168.10.23'}],
 users:[{id:'u1',name:'演示管理员',role:'系统管理员',scope:'全船',enabled:true},{id:'u2',name:'轮机负责人',role:'资产管理员',scope:'动力区域',enabled:true},{id:'u3',name:'管理查看者',role:'只读查看',scope:'全船',enabled:true}],
 settings:{low:20,weak:-80,offline:30,refresh:5},logs:[{time:'2026-09-14 09:20:00',action:'示例初始化',detail:'已载入海澜 01 资产、标签及演示任务'}]
});
let db;try{db=JSON.parse(localStorage.getItem(STORE));if(db?.version!==1)db=seed();}catch{db=seed();}
let storageAvailable=true;const persist=()=>{try{localStorage.setItem(STORE,JSON.stringify(db));}catch{storageAvailable=false;$('.demo-strip span').textContent='当前环境无法保存，修改仅本次有效';}};
let route={page:'overview',tab:''},folder='root',query='',filter='all',groupFilter='',selected=new Set(),importRows=[],docOpen=innerWidth>1080,toastTimer,pendingNav=null;
const asset=id=>db.assets.find(a=>a.id===id),label=id=>db.labels.find(l=>l.id===id),tpl=id=>db.templates.find(t=>t.id===id),dir=id=>db.dirs.find(d=>d.id===id);
const labelFor=a=>db.labels.find(l=>l.asset===a.id);
const path=id=>{let d=dir(id);return d?(d.parent==='root'?d.name:path(d.parent)+' / '+d.name):db.ship.name;};
const depth=id=>id==='root'?0:1+depth(dir(id)?.parent||'root');
const within=(id,parent)=>parent==='root'||id===parent||(dir(id)&&within(dir(id).parent,parent));
const assetsIn=id=>db.assets.filter(a=>within(a.dir,id));
const labelName=l=>asset(l.asset)?.name||'未绑定资产';
const updateStatus=l=>!l.asset?'unbound':l.published===l.version?'synced':db.tasks.some(t=>t.items.some(i=>i.label===l.id&&i.version===l.version&&i.status==='waiting'))?'waiting':'outdated';
const stateText=l=>l.state==='paused'?'停用':l.asset?'在用':'待绑定';
const badge=(text,kind='')=>`<span class="pill ${kind}">${esc(text)}</span>`;
const onlineBadge=l=>badge(l.online?'在线':'离线',l.online?'':'neutral');
const updateBadge=l=>{const s=updateStatus(l);return badge({unbound:'未绑定',synced:'已确认更新',waiting:'结果待确认',outdated:'待更新'}[s],{unbound:'neutral',synced:'',waiting:'blue',outdated:'warn'}[s]);};
const action=(name,text,id='',cls='btn small')=>`<button type="button" class="${cls}" data-action="${name}" data-id="${esc(id)}">${text}</button>`;
const log=(a,d)=>{db.logs.unshift({time:stamp(),action:a,detail:d});persist();};
function toast(s){clearTimeout(toastTimer);$('#toast').textContent=s;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function modal(title,body,wide=false){const d=$('#dialog');d.classList.toggle('wide',wide);$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;if(!d.open)d.showModal();}
const closeModal=()=>$('#dialog').close();
const footerForm=(text='保存')=>`<div class="form-error" role="alert" id="form-error"></div><div class="form-actions">${action('close-dialog','取消')}<button class="btn primary" type="submit">${text}</button></div>`;
const inputField=(name,title,value='',type='text',required=false)=>`<label class="form-field">${title}${required?' *':''}<input name="${name}" value="${esc(value)}" type="${type}" ${required?'required':''} maxlength="100"></label>`;
const dirOptions=(value,allowRoot=false)=>`${allowRoot?`<option value="root" ${value==='root'?'selected':''}>船舶根目录</option>`:''}`+db.dirs.map(d=>`<option value="${d.id}" ${value===d.id?'selected':''}>${esc(path(d.id))}</option>`).join('');
const templateOptions=v=>db.templates.map(t=>`<option value="${t.id}" ${v===t.id?'selected':''}>${esc(t.name)}</option>`).join('');
const groupOptions=v=>db.groups.map(g=>`<option value="${g.id}" ${g.id===v?'selected':''}>${esc(g.name)}</option>`).join('');
const head=(title,subtitle,buttons='')=>`<div class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="actions">${buttons}</div></div>`;
const panel=(title,body,extra='')=>`<section class="panel"><div class="panel-head"><h3>${title}</h3>${extra}</div>${body}</section>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}"><div class="empty"><strong>没有符合条件的数据</strong>试试其他目录、分组或搜索条件。</div></td></tr>`}</tbody></table></div>`;
const foot=count=>`<div class="table-footer"><span>共 ${count} 条 · 演示数据</span><span>全部显示</span></div>`;
const svg=path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${path}</svg>`;
const icons={overview:svg('<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>'),storage:svg('<path d="M3 6h7l2 3h9v11H3zM3 6V4h7l2 2h9v3"/>'),labels:svg('<path d="M3 4h11l7 8-8 8L3 10z"/><circle cx="8" cy="8" r="1.5"/>'),status:svg('<path d="M3 12h4l3-7 4 14 3-7h4M3 3h18v18H3z"/>'),system:svg('<circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>')};
const pages={overview:'全船看板',storage:'仓储管理',labels:'标签管理',status:'标签状态',system:'系统管理'};
const tabs={labels:[['devices','标签台账'],['groups','标签分组'],['data','字段与数据'],['templates','模板设计'],['tasks','更新任务'],['strategies','标签策略']],system:[['gateways','网关管理'],['users','账号权限'],['settings','基础设置'],['logs','操作日志']]};
const tabBar=()=>tabs[route.page]?`<nav class="tabs" aria-label="${pages[route.page]}子功能">${tabs[route.page].map(([id,name])=>`<a href="#${route.page}/${id}" class="${route.tab===id?'active':''}" ${route.tab===id?'aria-current="page"':''}>${name}</a>`).join('')}</nav>`:'';
const coverage={storage:[0,2,3,4],devices:[0,1,6,10,11,14],groups:[2],data:[3,4,5,6],templates:[7,8],tasks:[10,11],strategies:[12,13],status:[0,1,2,3,4,5],overview:[0,1,2,3,4,5,6],gateways:[1],users:[2],settings:[0,3],logs:[4]};
// Requirements navigate to UI, never execute a save, download or device command.
const requirementDemos={
 '0-0':{route:'storage',target:'.tree-panel',name:'仓储管理 · 三级目录'},
 '0-2':{route:'storage',target:'.compact-stats',name:'仓储管理 · 目录概览'},
 '0-3':{route:'storage',target:'.storage-layout .panel',name:'仓储管理 · 下属资产与标签'},
 '0-4':{route:'storage',open:'move',target:'[name="dir"]',name:'仓储管理 · 调整资产归属'},
 '1-0':{route:'labels/devices',target:'.table-wrap',name:'标签管理 · 标签台账'},
 '1-1':{route:'labels/devices',open:'bind',target:'[data-form="bind"]',name:'标签管理 · 资产绑定'},
 '1-2':{route:'labels/groups',target:'.panel',name:'标签管理 · 标签分组'},
 '1-3':{route:'labels/data',open:'field',target:'[data-form="field"]',name:'字段与数据 · 字段配置'},
 '1-4':{route:'labels/data',open:'asset',target:'[data-form="asset"]',name:'字段与数据 · 资产录入'},
 '1-5':{route:'labels/data',open:'import',target:'#csv-input',name:'字段与数据 · 批量导入'},
 '1-6':{route:'labels/data',target:'[data-action="export-assets"]',name:'字段与数据 · 数据导出'},
 '1-7':{route:'labels/templates',open:'template',target:'#live-preview',name:'模板设计 · 编辑与实时预览'},
 '1-8':{route:'labels/templates',target:'.template-grid',name:'模板设计 · 模板管理'},
 '1-10':{route:'labels/tasks',open:'publish',target:'[data-form="publish"]',name:'更新任务 · 创建下发任务'},
 '1-11':{route:'labels/tasks',target:'.panel',name:'标签管理 · 更新任务'},
 '1-12':{route:'labels/strategies',open:'strategy',target:'[data-form="strategy"]',name:'标签策略 · 条件与优先级'},
 '1-13':{route:'labels/strategies',open:'strategy',target:'[name="schedule"]',name:'标签策略 · 刷新计划'},
 '1-14':{route:'labels/devices',open:'label',target:'[data-action="led"]',name:'标签详情 · LED 控制'},
 '2-0':{route:'status',target:'.table-wrap',name:'标签状态 · 状态列表'},
 '2-1':{route:'status',target:'.toolbar',name:'标签状态 · 搜索与筛选'},
 '2-2':{route:'status',open:'label',target:'.status-grid',name:'标签状态 · 单标签详情'},
 '2-3':{route:'status',filter:'offline',target:'.panel',name:'标签状态 · 离线异常筛选'},
 '2-4':{route:'labels/tasks',open:'failed-task',target:'[data-action="task-retry"]',name:'更新任务 · 查看异常与重试'},
 '2-5':{route:'status',target:'[data-action="export-labels"]',name:'标签状态 · 查询与导出'},
 '3-0':{route:'overview',target:'.stats',name:'全船看板 · 资产与标签总览'},
 '3-1':{route:'status',target:'.page-head + .actions',name:'标签状态 · 运行概况'},
 '3-2':{route:'labels/tasks',target:'.panel',name:'更新任务 · 执行概况'},
 '3-3':{route:'overview',target:'.dashboard-grid .panel:first-child',name:'全船看板 · 舱室与部位分布'},
 '3-4':{route:'overview',target:'[data-search]',name:'全船看板 · 全船信息查询'},
 '3-5':{route:'overview',target:'.dashboard-grid .panel:last-child',name:'全船看板 · 异常与待办'},
 '3-6':{route:'status',target:'[data-action="refresh-status"]',name:'标签状态 · 刷新示例数据'},
 '4-0':{route:'system/settings',target:'[name="shipName"]',name:'基础设置 · 船舶信息'},
 '4-1':{route:'system/gateways',target:'.panel',name:'系统管理 · 网关管理'},
 '4-2':{route:'system/users',open:'user',target:'[data-form="user"]',name:'系统管理 · 账号与权限'},
 '4-3':{route:'system/settings',target:'.settings-list',name:'系统管理 · 基础参数'},
 '4-4':{route:'system/logs',target:'.panel',name:'系统管理 · 操作日志'}
};
let pendingRequirement=null,requirementHighlightTimer;
function openRequirementDemo(id){const demo=requirementDemos[id];if(!demo)return;pendingRequirement=demo;if(innerWidth<=1080)docOpen=false;go(...demo.route.split('/'));}
function revealRequirement(demo){
 const a=assetsIn(folder)[0]||db.assets[0],l=db.labels.find(l=>l.asset===a?.id)||db.labels[0];
 if(demo.filter){filter=demo.filter;render();}
 switch(demo.open){
  case 'move':if(a){assetDetail(a.id);document.querySelector('#dialog [data-action="asset-move"]').click();}break;
  case 'bind':bindForm(a?.id);break;
  case 'field':document.querySelector('#main [data-action="field-edit"]').click();break;
  case 'asset':assetForm(a?.id);break;
  case 'import':importForm();break;
  case 'template':templateForm(db.templates[0]?.id);break;
  case 'publish':publishForm();break;
  case 'strategy':strategyForm(db.strategies[0]?.id);break;
  case 'label':if(l)labelDetail(l.id);break;
  case 'failed-task':{const t=db.tasks.find(t=>t.items.some(i=>i.status==='failed'))||db.tasks[0];if(t)taskDetail(t.id);break;}
  case 'user':simpleForm('user',db.users[0]?.id);break;
 }
 const scope=$('#dialog').open?$('#dialog'):$('#main');
 const target=scope.querySelector(demo.target)||scope.querySelector('.panel')||scope;
 clearTimeout(requirementHighlightTimer);$$('.requirement-highlight').forEach(el=>el.classList.remove('requirement-highlight'));
 target.classList.add('requirement-highlight');if(!target.matches('input,select,textarea,button,a[href]'))target.setAttribute('tabindex','-1');
 target.focus({preventScroll:true});target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});
 requirementHighlightTimer=setTimeout(()=>target.classList.remove('requirement-highlight'),3200);
 toast('已定位：'+demo.name);
}
function reqPanel(){const index={storage:0,labels:1,status:2,overview:3,system:4}[route.page],key=route.tab||route.page;const indices=coverage[key]||[];const section=['4.1 仓储管理','4.2 标签管理','4.3 标签状态','4.4 全船看板','4.5 系统管理'][index];
 $('#requirements').innerHTML=`<div class="req-top"><h3>产品需求对照</h3>${action('toggle-doc','×','','icon-btn')}</div><div class="req-version">产品文档 v0.1 / ${section}</div><p class="req-foot" style="border:0;padding:0 0 15px">点击下方演示入口，跳转并高亮对应功能；需要填写的功能会打开演示窗口。实际接口和业务规则待后续细化。</p>`+indices.map(i=>{const r=DOC.requirements[index][i],sketch=(key==='users'||(key==='data'&&i===5)||(key==='templates'&&i===7)||(key==='strategies'&&i===13)||(key==='status'&&i===3));return `<article class="req-item"><span class="req-number">${section.slice(0,3)} · ${String(i+1).padStart(2,'0')}</span><h3>${esc(r.title)}</h3><p>${esc(r.text)}</p><button type="button" class="coverage req-demo ${sketch?'sketch':''}" data-action="requirement-demo" data-id="${index}-${i}" title="前往：${esc(requirementDemos[index+'-'+i].name)}" aria-label="${esc(r.title)}：前往对应功能演示">${sketch?'查看简化演示':'可点击演示'} <span aria-hidden="true">↗</span></button>${sketch?'<small class="req-scope">部分需求待细化</small>':''}</article>`;}).join('')+`<div class="req-foot">${key==='data'?'导入原型支持 CSV；Excel、多类型完整校验在正式开发时补齐。':key==='templates'?'当前支持文本字段版式预览；图片、二维码、条形码与完整拖拽编辑器待细化。':key==='strategies'?'可配置计划并手动模拟执行，不会后台定时运行。':key==='users'?'账号和权限为配置演示，不做真实登录或权限拦截。':'所有状态、下发与回执均在本地模拟。'}</div><div style="margin-top:18px">${action('document','浏览完整产品文档 ↗')}</div>`;
 document.body.classList.toggle('doc-hidden',!docOpen);$('.doc-toggle').setAttribute('aria-expanded',String(docOpen));}
function readRoute(){const [page,tab]=(location.hash.slice(1)||'overview').split('/');route.page=pages[page]?page:'overview';route.tab=tabs[route.page]?.some(t=>t[0]===tab)?tab:tabs[route.page]?.[0][0]||'';query='';filter='all';selected.clear();groupFilter=pendingNav?.groupFilter||'';pendingNav=null;render();document.body.classList.remove('nav-open');window.scrollTo(0,0);if(pendingRequirement){const demo=pendingRequirement;pendingRequirement=null;requestAnimationFrame(()=>revealRequirement(demo));}}
function go(page,tab=''){const hash='#'+page+(tab?'/'+tab:'');if(location.hash===hash){readRoute();}else location.hash=hash;}
function render(){
 $('#nav').innerHTML='<div class="nav-caption">工作空间</div>'+Object.entries(pages).map(([id,name])=>`<a href="#${id}" class="nav-link ${route.page===id?'active':''}" ${route.page===id?'aria-current="page"':''}>${icons[id]}${name}</a>`).join('');
 $('#breadcrumb').textContent=db.ship.name+' / '+pages[route.page]+(route.tab?' / '+tabs[route.page].find(t=>t[0]===route.tab)[1]:'');$('.ship strong').textContent=db.ship.name;$('.ship>span:last-child').textContent=db.ship.code+' / 单船管理';
 const fn=route.page==='overview'?overview:route.page==='storage'?storage:route.page==='status'?statusPage:route.page==='labels'?({devices:devices,groups:groups,data:dataPage,templates:templates,tasks:tasks,strategies:strategies}[route.tab]):({gateways:gateways,users:users,settings:settings,logs:logs}[route.tab]);
 $('#main').innerHTML=fn();reqPanel();}
function overview(){const bound=db.labels.filter(l=>l.asset),online=db.labels.filter(l=>l.online),bad=db.labels.filter(l=>!l.online||l.battery<db.settings.low||l.rssi<db.settings.weak),pending=bound.filter(l=>updateStatus(l)!=='synced');
 const stats=[['设备资产',db.assets.length,`已配置标签 ${bound.length} 台`,'storage'],['电子标签',db.labels.length,`待绑定 ${db.labels.filter(l=>!l.asset&&l.state!=='paused').length} 枚`,'labels'],['在线标签',online.length,`在线率 ${Math.round(online.length/db.labels.length*100)}%`,'status'],['待更新标签',pending.length,'包含待下发与结果待确认','tasks']];
 const todos=bad.slice(0,4).map(l=>`<div class="todo"><span class="todo-mark">!</span><div class="todo-text"><strong>${esc(labelName(l))}</strong><small>${!l.online?'标签离线':l.battery<db.settings.low?'电量不足 '+l.battery+'%':'弱信号 '+l.rssi+' dBm'} · ${esc(l.mac.slice(-8))}</small></div>${action('label-detail','查看',l.id,'link-btn')}</div>`).join('');
 const dist=db.dirs.filter(d=>d.parent==='root').map(d=>{const n=assetsIn(d.id).length;return `<div class="bar-row"><div class="bar-label">${action('open-folder',esc(d.name),d.id,'link-btn')}<span>${n} 台资产</span></div><div class="bar"><span style="width:${Math.max(4,n/db.assets.length*100)}%"></span></div></div>`;}).join('');
 const rows=db.assets.filter(a=>!query||[a.name,a.code,path(a.dir)].join(' ').includes(query)).map(a=>{const l=labelFor(a);return `<tr><td>${action('asset-detail',esc(a.name),a.id,'link-btn')}<small>${esc(a.code)}</small></td><td>${esc(dir(a.dir)?.name)}</td><td>${esc(a.team)}</td><td>${l?onlineBadge(l):badge('未绑定','neutral')}</td><td>${l?updateBadge(l):'—'}</td><td>${action('asset-detail','详情',a.id,'link-btn')}</td></tr>`;}).join('');
 return head('全船看板','资产、标签与待办的全局视图 · 数据为本地示例',action('guide','演示路线 ↗'))+`<div class="stats">${stats.map(([c,n,s,target])=>`<div class="stat interactive" role="button" tabindex="0" data-action="stat-nav" data-id="${target}"><span class="caption">${c}</span><strong>${n}</strong><small>${s}</small></div>`).join('')}</div><div class="dashboard-grid">${panel('舱室 / 部位分布',`<div class="panel-body">${dist}<div class="legend"><span><i class="dot"></i>按主目录统计资产</span><span>点击部位进入下属数据</span></div></div>`)}${panel('异常与待处理',`<div class="panel-body" style="padding-top:4px;padding-bottom:4px">${todos||'<p class="empty">当前没有异常</p>'}</div>`,action('stat-nav','全部状态 →','status','link-btn'))}</div>`+panel('全船设备标签信息',`<div class="toolbar"><input aria-label="搜索全船资产" data-search placeholder="搜索设备名称、编码或舱室" value="${esc(query)}"></div>${table(['设备资产','所在部位','责任班组','在线状态','更新状态','操作'],rows)}${foot(db.assets.filter(a=>!query||[a.name,a.code,path(a.dir)].join(' ').includes(query)).length)}`);
}
function tree(parent='root'){return db.dirs.filter(d=>d.parent===parent).map(d=>`<button class="tree-node ${folder===d.id?'active':''}" data-action="folder" data-id="${d.id}"><span class="node-icon">▱</span>${esc(d.name)}<span class="count">${assetsIn(d.id).length}</span></button>${db.dirs.some(x=>x.parent===d.id)?`<div class="tree-indent">${tree(d.id)}</div>`:''}`).join('');}
function assetRows(items){return items.map(a=>{const l=labelFor(a);return `<tr><td>${action('asset-detail',esc(a.name),a.id,'link-btn')}<small>${esc(a.code)}</small></td><td>${esc(dir(a.dir)?.name)}</td><td>${esc(a.team)}</td><td>${l?`<small>${esc(l.mac.slice(-8))}</small>${onlineBadge(l)}`:badge('待绑定','warn')}</td><td><div class="actions">${action('asset-edit','编辑',a.id,'link-btn')}${action('asset-detail','详情',a.id,'link-btn')}</div></td></tr>`;}).join('');}
function storage(){const all=assetsIn(folder),items=all.filter(a=>[a.name,a.code,a.team].join(' ').includes(query)),bound=all.filter(a=>labelFor(a));return head('仓储管理','按舱室或功能部位组织设备，最多三级目录',action('directory-add','＋ 新建目录'))+`<div class="storage-layout"><aside class="tree-panel"><div class="tree-head"><h3>船舶目录</h3><span class="small-label">最多三级</span></div><button class="tree-node ${folder==='root'?'active':''}" data-action="folder" data-id="root"><span class="node-icon">◇</span>${esc(db.ship.name)}<span class="count">${db.assets.length}</span></button><div class="tree-indent">${tree()}</div></aside><div><div class="directory-path">${esc(path(folder))}</div><div class="row-between" style="margin-bottom:16px"><h2>${folder==='root'?'全船资产':esc(dir(folder)?.name)}</h2><div class="actions">${folder!=='root'?action('directory-edit','编辑目录',folder):''}${action('asset-add','＋ 新增资产','','btn primary')}</div></div><div class="compact-stats"><div>设备资产<strong>${all.length}</strong></div><div>已绑定<strong>${bound.length}</strong></div><div>待绑定<strong>${all.length-bound.length}</strong></div></div><div class="panel"><div class="toolbar"><input data-search aria-label="搜索当前目录资产" placeholder="搜索名称、编码或班组" value="${esc(query)}">${action('export-assets','导出 CSV')}</div>${table(['设备资产','部位','班组','标签','操作'],assetRows(items))}${foot(items.length)}</div><p class="status-note">当前包含下级目录的资产。资产详情中可迁移归属、绑定或更换标签。</p></div></div>`;}
function filteredLabels(){return db.labels.filter(l=>{const a=asset(l.asset),q=[l.mac,a?.name,a?.code,a?.team,path(a?.dir)].join(' ').includes(query);let ok=filter==='all'||(filter==='online'&&l.online)||(filter==='offline'&&!l.online)||(filter==='low'&&l.battery<db.settings.low)||(filter==='weak'&&l.rssi<db.settings.weak)||(filter==='outdated'&&l.asset&&updateStatus(l)!=='synced')||(filter==='unbound'&&!l.asset);return q&&ok&&(!groupFilter||db.groups.find(g=>g.id===groupFilter)?.members.includes(l.id));});}
function labelToolbar(){return `<div class="toolbar"><input data-search aria-label="搜索标签或设备" placeholder="搜索 MAC、设备名称或编码" value="${esc(query)}"><select data-filter aria-label="筛选标签状态">${[['all','全部标签'],['online','在线'],['offline','离线'],['low','低电量'],['weak','弱信号'],['outdated','待更新'],['unbound','未绑定']].map(([v,t])=>`<option value="${v}" ${filter===v?'selected':''}>${t}</option>`).join('')}</select><select data-group-filter aria-label="筛选标签分组"><option value="">全部分组</option>${groupOptions(groupFilter)}</select>${action('export-labels','导出 CSV')}</div>`;}
function labelTable(status=false){const items=filteredLabels();return (selected.size?`<div class="selection-bar"><span>已选择 ${selected.size} 枚标签</span>${action('publish-selected','下发更新','','btn small primary')}${action('group-selected','加入分组')}${action('clear-selection','清除选择','','link-btn')}</div>`:'')+table([`<input type="checkbox" aria-label="全选当前标签" data-select-all ${items.length&&items.every(l=>selected.has(l.id))?'checked':''}>`,'标签 / 设备',status?'电量 / 信号':'所属部位','在线状态','内容状态','操作'],items.map(l=>{const a=asset(l.asset);return `<tr><td><input type="checkbox" aria-label="选择 ${esc(l.mac)}" data-select="${l.id}" ${selected.has(l.id)?'checked':''}></td><td>${action('label-detail',esc(a?.name||'未绑定资产'),l.id,'link-btn')}<small>${esc(l.mac)}</small></td><td>${status?`${badge(l.battery+'%',l.battery<db.settings.low?'warn':'neutral')}<small>${l.rssi} dBm</small>`:esc(a?dir(a.dir)?.name:'—')}</td><td>${onlineBadge(l)}${l.state==='paused'?'<small>已停用</small>':''}</td><td>${updateBadge(l)}</td><td>${action('label-detail','详情',l.id,'link-btn')}</td></tr>`;}).join(''))+foot(items.length);}
function devices(){return head('标签管理','管理显示硬件、资产绑定及批量更新',action('label-add','＋ 登记标签','','btn primary'))+tabBar()+`<div class="panel">${labelToolbar()}${labelTable()}</div>`;}
function groups(){return head('标签分组','分组可跨目录，用于按设备类型或班组批量操作',action('group-edit','＋ 新增分组','','btn primary'))+tabBar()+`<div class="panel">${db.groups.map(g=>`<div class="group-row"><div class="group-main"><h3>${esc(g.name)}</h3><p>${esc(g.description||'暂无描述')}</p></div><div class="member-count"><strong>${g.members.length}</strong>枚标签</div><div class="actions">${action('group-open','查看标签',g.id)}${action('group-edit','编辑成员',g.id)}${action('group-publish','批量下发',g.id,'btn primary')}</div></div>`).join('')||'<div class="empty">还没有分组，可新建并选择成员。</div>'}</div><div class="hint">分组与位置目录相互独立。同一标签可参与不同用途的分组，位置归属保持唯一。</div>`;}
function dataPage(){const items=db.assets.filter(a=>[a.name,a.code,a.team].join(' ').includes(query));return head('字段与资产数据','先定义字段，再录入或批量导入设备信息',action('import','批量导入','','btn primary'))+tabBar()+panel('字段配置',`<div class="panel-body"><div class="actions">${db.fields.map(f=>action('field-edit',esc(f.name)+(f.required?' *':''),f.id)).join('')}</div><p class="status-note">点击字段查看配置。内置设备编码、名称和位置用于关联资产，不可移除。</p></div>`,action('field-add','＋ 自定义字段','','link-btn'))+`<div class="panel"><div class="toolbar"><input data-search aria-label="搜索资产数据" placeholder="搜索设备名称、编码或班组" value="${esc(query)}">${action('asset-add','新增资产')}${action('export-assets','导出 CSV')}${action('download-import','下载导入模板')}</div>${table(['设备资产','部位','班组','标签','操作'],assetRows(items))}${foot(items.length)}</div>`;}
function preview(t,a=db.assets[0]){return `<div class="eink" style="--tag-color:${esc(t.color)}"><div class="eink-top"><strong>${esc(t.heading)}</strong><span>${esc(a.code||'设备编码')}</span></div><div class="eink-name">${esc(a.name||'设备名称')}</div><div class="eink-code">${t.showModel?'型号 '+esc(a.model||'—'):'&nbsp;'}</div><div class="eink-bottom"><span>${esc(dir(a.dir)?.name||'所属部位')}</span><span>${t.showOwner?esc(a.team||'责任班组')+' · '+esc(a.owner||'责任人'):''}</span></div></div>`;}
function templates(){return head('模板设计','2.9 英寸 · 296 × 128 像素 · 黑白红黄屏幕示例',action('template-edit','＋ 新建模板','','btn primary'))+tabBar()+`<div class="hint">可编辑标题、显示颜色和字段显隐，实时查看简化版标签效果。预览为版式示意，尚非硬件像素验收效果。</div><div class="template-grid">${db.templates.map(t=>`<article class="template-card"><div class="preview-zone">${preview(t)}</div><div class="template-info"><div class="row-between"><h3>${esc(t.name)}</h3>${badge('v'+t.revision,'neutral')}</div><p>已关联 ${db.labels.filter(l=>l.template===t.id).length} 枚标签 · 2.9 英寸</p><div class="actions">${action('template-edit','编辑模板',t.id)}${action('template-copy','复制',t.id)}${action('template-apply','应用到标签',t.id,'btn primary')}</div></div></article>`).join('')}</div>`;}
function tasks(){return head('更新任务','追踪从提交到屏幕回执的执行结果',action('publish-all','创建下发任务','','btn primary'))+tabBar()+`<div class="hint">模拟下发后，点击“模拟回执”查看执行结果。离线标签保留待确认；恢复在线后可再次模拟回执。</div><div class="panel">${table(['任务名称','范围 / 进度','状态','创建时间','操作'],db.tasks.map(t=>{const n=t.items.length,s=t.items.filter(i=>i.status==='success').length,f=t.items.filter(i=>i.status==='failed').length;return `<tr><td>${action('task-detail',esc(t.name),t.id,'link-btn')}<small>${esc(t.id)}</small></td><td>${s} / ${n} 已确认</td><td>${s===n?badge('已确认更新'):f?badge('有失败项','bad'):badge('结果待确认','blue')}</td><td><small>${esc(t.time)}</small></td><td>${action('task-detail','查看任务',t.id,'link-btn')}</td></tr>`;}).join(''))}${foot(db.tasks.length)}</div>`;}
function strategies(){return head('标签策略','按条件匹配模板，再按计划触发内容更新',action('strategy-edit','＋ 新增策略','','btn primary'))+tabBar()+`<div class="hint">数字越小优先级越高；同优先级按列表顺序匹配。可手动模拟执行，定时和周期计划仅保存配置。</div><div class="panel">${[...db.strategies].sort((a,b)=>a.priority-b.priority).map(r=>`<div class="group-row"><span class="priority">${r.priority}</span><div class="group-main"><h3>${esc(r.name)}</h3><p class="rules-condition">${r.field==='all'?'所有标签 / 默认规则':esc(db.fields.find(f=>f.id===r.field)?.name||r.field)+' 等于「'+esc(r.value)+'」'} → ${esc(tpl(r.template)?.name)}</p><p>范围：${r.scope==='all'?'全船已绑定标签':esc(db.groups.find(g=>g.id===r.scope)?.name||'分组已删除')} · ${esc(r.schedule)}</p></div><button class="switch ${r.enabled?'on':''}" role="switch" aria-checked="${r.enabled}" aria-label="启停 ${esc(r.name)}" data-action="strategy-toggle" data-id="${r.id}"></button>${action('strategy-edit','编辑',r.id)}</div>`).join('')}<div class="panel-body">${action('strategy-run','模拟匹配并创建下发任务','','btn primary')}</div></div>`;}
function statusPage(){const offline=db.labels.filter(l=>!l.online).length,low=db.labels.filter(l=>l.battery<db.settings.low).length,weak=db.labels.filter(l=>l.rssi<db.settings.weak).length;return head('标签状态','分别查看通信健康、使用状态与内容更新结果',action('refresh-status','刷新示例状态'))+`<div class="actions" style="margin-bottom:20px">${[['all','全部 '+db.labels.length],['offline','离线 '+offline],['low','低电量 '+low],['weak','弱信号 '+weak]].map(([id,t])=>action('status-filter',t,id,'btn status-filter '+(filter===id?'active':''))).join('')}</div><div class="panel">${labelToolbar()}${labelTable(true)}</div><p class="status-note">离线、低电量和弱信号可重叠。最后上报时间和回执均为演示数据；后台刷新不代表标签屏幕刷新。</p>`;}
function gateways(){return head('系统管理','管理网关、权限与运行参数',action('gateway-edit','＋ 新增网关','','btn primary'))+tabBar()+`<div class="panel">${table(['网关','安装位置','关联标签','连接状态','操作'],db.gateways.map(g=>`<tr><td><strong>${esc(g.name)}</strong><small>${esc(g.ip)}</small></td><td>${esc(path(g.dir))}</td><td>${db.labels.filter(l=>l.gateway===g.id).length} 枚</td><td>${onlineBadge(g)}</td><td>${action('gateway-edit','查看 / 编辑',g.id,'link-btn')}</td></tr>`).join(''))}</div>`;}
function users(){return head('账号与权限','配置演示账号的角色和数据范围',action('user-edit','＋ 新增账号','','btn primary'))+tabBar()+`<div class="hint warn">权限为产品配置示意。本原型始终使用演示管理员，不进行真实登录或权限拦截。</div><div class="panel">${table(['账号','角色','数据范围','状态','操作'],db.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.role)}</td><td>${esc(u.scope)}</td><td>${badge(u.enabled?'启用':'停用',u.enabled?'':'neutral')}</td><td>${action('user-edit','配置权限',u.id,'link-btn')}</td></tr>`).join(''))}</div>`;}
function settings(){return head('基础设置','本地配置示例，保存后阈值用于本原型的异常筛选')+tabBar()+`<section class="panel"><div class="panel-body"><form data-form="settings" class="settings-list"><div class="form-grid">${inputField('shipName','船舶名称',db.ship.name,'text',true)}${inputField('shipCode','船舶编号',db.ship.code,'text',true)}</div><div style="margin-top:22px">${[['low','低电量阈值','电量低于此值时标记低电量，单位 %',0,100],['weak','弱信号阈值','RSSI 低于此值时标记弱信号，单位 dBm',-120,-1],['offline','离线判定间隔','单位分钟；原型通过手动模拟在线状态',1,1440],['refresh','看板刷新间隔','单位分钟；仅保存配置，不自动轮询',1,1440]].map(([k,t,d,min,max])=>`<label class="setting"><div><h3>${t}</h3><p>${d}</p></div><input type="number" name="${k}" value="${db.settings[k]}" min="${min}" max="${max}" required></label>`).join('')}</div><div class="form-error" id="form-error"></div><div class="form-actions"><button class="btn primary">保存设置</button></div></form></div></section>`;}
function logs(){return head('操作日志','记录当前浏览器中的资产变更与模拟操作')+tabBar()+`<div class="panel">${table(['时间','操作人','操作','内容'],db.logs.slice(0,100).map(l=>`<tr><td><small>${esc(l.time)}</small></td><td>演示管理员</td><td>${esc(l.action)}</td><td style="white-space:normal;min-width:200px">${esc(l.detail)}</td></tr>`).join(''))}${foot(Math.min(100,db.logs.length))}</div>`;}

function assetDetail(id){const a=asset(id);if(!a)return;const l=labelFor(a);modal(a.name,`<div class="detail-grid">${[['设备编码',a.code],['设备型号',a.model],['所属目录',path(a.dir)],['责任班组',a.team],['责任人',a.owner],['关联标签',l?.mac||'暂无']].map(([k,v])=>`<div class="detail-item"><span>${k}</span>${esc(v||'—')}</div>`).join('')}</div><hr class="detail-divider"><h3>标签关联</h3><p class="status-note">资产与在用标签按一对一关系演示，更换后旧标签保留为待绑定。</p><div class="actions">${action('asset-edit','编辑信息',a.id)}${action('asset-move','调整归属',a.id)}${action('bind','绑定 / 更换标签',a.id,'btn primary')}${l?action('label-detail','查看标签',l.id):''}</div>`);}
function assetForm(id){const a=asset(id)||{id:'',dir:folder==='root'?'d3':folder};modal(id?'编辑资产信息':'新增设备资产',`<form data-form="asset" data-id="${esc(a.id)}"><div class="form-grid">${db.fields.filter(f=>f.id!=='dir').map(f=>inputField(f.id,esc(f.name),a[f.id]||'',f.type==='数字'?'number':'text',f.required)).join('')}<label class="form-field full">所属目录 *<select name="dir" required>${dirOptions(a.dir)}</select></label></div><p class="status-note">变更显示字段后，关联标签将标记为待更新。</p>${footerForm()}</form>`);}
function labelDetail(id){const l=label(id);if(!l)return;const a=asset(l.asset),t=tpl(l.template);modal('标签详情 · '+l.mac.slice(-5),`<div class="detail-grid"><div class="detail-item"><span>标签 MAC</span>${esc(l.mac)}</div><div class="detail-item"><span>型号 / 屏幕</span>STag29AQ · 2.9 英寸</div><div class="detail-item"><span>关联资产</span>${a?action('asset-detail',esc(a.name),a.id,'link-btn'):'未绑定'}</div><div class="detail-item"><span>所属目录</span>${a?esc(path(a.dir)):'—'}</div></div><div class="status-grid"><div class="status-cell"><small>使用状态</small><strong>${stateText(l)}</strong><small>绑定关系独立于通信</small></div><div class="status-cell"><small>通信状态</small><strong>${onlineBadge(l)}</strong><small>电量 ${l.battery}% · ${l.rssi} dBm</small></div><div class="status-cell"><small>内容状态</small><strong>${updateBadge(l)}</strong><small>已确认 v${l.published} / 目标 v${l.version}</small></div></div><div class="detail-grid"><div class="detail-item"><span>最后上报</span>${esc(l.last)}</div><div class="detail-item"><span>关联网关</span>${esc(db.gateways.find(g=>g.id===l.gateway)?.name||'未指定')}</div></div><hr class="detail-divider"><div class="row-between"><h3>目标内容预览</h3>${badge(t?.name||'未配置','neutral')}</div><div class="preview-zone" style="margin:15px 0">${preview(t||db.templates[0],a||{name:'待绑定标签',code:l.mac.slice(-8)})}</div><p class="status-note">此处为目标内容；是否已经显示在现场屏幕上，需要单独查看任务回执。</p><div class="actions">${a?action('publish-one','下发此标签',l.id,'btn primary'):action('bind-label','绑定资产',l.id,'btn primary')}${action('simulate-online',l.online?'模拟离线':'模拟恢复在线',l.id)}${action('led','模拟点灯',l.id)}${a?action('unbind','解除绑定',l.id):''}${action('toggle-paused',l.state==='paused'?'启用标签':'停用标签',l.id)}</div><hr class="detail-divider"><h3>最近更新任务</h3><ul class="timeline">${db.tasks.filter(t=>t.items.some(i=>i.label===l.id)).slice(0,4).map(t=>`<li>${action('task-detail',esc(t.name),t.id,'link-btn')}<small>${esc(t.time)}</small></li>`).join('')||'<li>暂无任务记录</li>'}</ul>`);}
function bindForm(assetId,labelId){modal('绑定资产与标签',`<form data-form="bind"><div class="form-grid"><label class="form-field full">设备资产<select name="asset">${db.assets.map(a=>`<option value="${a.id}" ${a.id===assetId?'selected':''}>${esc(a.code+' · '+a.name)}${labelFor(a)?'（已绑定，将更换）':''}</option>`).join('')}</select></label><label class="form-field full">电子标签<select name="label">${db.labels.filter(l=>!l.asset||l.asset===assetId).map(l=>`<option value="${l.id}" ${l.id===labelId?'selected':''}>${esc(l.mac)}${l.state==='paused'?'（停用，需先启用）':''}</option>`).join('')}</select></label></div><p class="status-note">绑定后标记为待更新，可从标签详情创建首次下发任务。</p>${footerForm('确认绑定')}</form>`);}
function publishForm(ids){const candidates=db.labels.filter(l=>ids?.length?ids.includes(l.id):true);modal('创建标签下发任务',`<form data-form="publish"><label class="form-field">任务名称 *<input name="name" value="标签内容更新" required maxlength="60"></label><p class="status-note">仅可下发已绑定且启用的标签。离线标签可加入任务，等待恢复后确认结果。</p><div class="check-list">${candidates.map(l=>`<label class="check-row"><input type="checkbox" name="labels" value="${l.id}" ${l.asset&&l.state!=='paused'?'checked':'disabled'}><span>${esc(labelName(l))}<small style="display:block;margin:0">${esc(l.mac)}</small></span><small>${!l.asset?'未绑定':l.state==='paused'?'已停用':l.online?'在线':'离线'}</small></label>`).join('')}</div>${footerForm('模拟下发')}</form>`);}
function newTask(ids,name){const items=ids.map(id=>label(id)).filter(l=>l&&l.asset&&l.state!=='paused').map(l=>({label:l.id,version:l.version,status:'waiting'}));if(!items.length)return null;const t={id:uid('JOB'),name,time:stamp(),items};db.tasks.unshift(t);log('模拟下发',name+' · '+items.length+' 枚标签');return t;}
function taskDetail(id){const t=db.tasks.find(t=>t.id===id);if(!t)return;modal(t.name,`<p class="status-note">创建于 ${esc(t.time)} · ${t.items.length} 枚标签</p>${table(['标签 / 设备','目标版本','执行结果'],t.items.map(i=>{const l=label(i.label);return `<tr><td>${esc(labelName(l))}<small>${esc(l.mac)}</small></td><td>v${i.version}</td><td>${badge({success:'已确认更新',failed:'下发失败',waiting:'结果待确认'}[i.status],{success:'',failed:'bad',waiting:'blue'}[i.status])}${!l.online?'<small>标签当前离线</small>':''}</td></tr>`;}).join(''))}<p class="status-note">模拟回执只确认在线且未停用标签；离线项保留待确认。若任务版本落后于最新目标版本，标签仍会显示待更新。</p><div class="form-actions">${action('task-retry','重试失败项',t.id)}${action('task-receipt','模拟回执',t.id,'btn primary')}</div>`);}
function groupForm(id){const g=db.groups.find(g=>g.id===id)||{name:'',description:'',members:[]};modal(id?'编辑标签分组':'新建标签分组',`<form data-form="group" data-id="${esc(id||'')}"><div class="form-grid">${inputField('name','分组名称',g.name,'text',true)}${inputField('description','分组描述',g.description)}</div><p class="status-note">选择成员 · 可跨舱室，同一标签可以属于多个分组。</p><div class="check-list">${db.labels.map(l=>`<label class="check-row"><input type="checkbox" name="members" value="${l.id}" ${g.members.includes(l.id)?'checked':''}><span>${esc(labelName(l))}</span><small>${esc(l.mac.slice(-8))}</small></label>`).join('')}</div>${footerForm()}</form>${id?`<div style="margin-top:15px">${action('group-delete','删除分组',id,'link-btn')}</div>`:''}`);}
function templateForm(id){const t=tpl(id)||{name:'新模板',heading:'设备资产',color:'#202020',showModel:true,showOwner:true};modal(id?'编辑显示模板':'新建显示模板',`<form data-form="template" data-id="${esc(id||'')}"><div class="editor-layout"><div class="form-grid">${inputField('name','模板名称',t.name,'text',true)}${inputField('heading','屏幕标题',t.heading,'text',true)}<label class="form-field">标题颜色<select name="color" data-preview><option value="#202020" ${t.color==='#202020'?'selected':''}>黑色</option><option value="#ae2424" ${t.color==='#ae2424'?'selected':''}>红色</option><option value="#9b7600" ${t.color==='#9b7600'?'selected':''}>黄色（预览色）</option></select></label><label class="form-field">屏幕规格<input value="2.9 英寸 / 296 × 128" readonly></label><label class="check-row"><input name="showModel" type="checkbox" data-preview ${t.showModel?'checked':''}>显示设备型号</label><label class="check-row"><input name="showOwner" type="checkbox" data-preview ${t.showOwner?'checked':''}>显示责任信息</label><label class="form-field full">预览资产<select name="previewAsset" data-preview>${db.assets.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label></div><div><div id="live-preview" class="preview-zone">${preview(t)}</div><p class="status-note">实时显示示例资产字段。保存后关联标签将标记为待更新。</p></div></div>${footerForm('保存模板')}</form>`,true);$('#dialog [name="heading"]').setAttribute('data-preview','');}
function strategyForm(id){const r=db.strategies.find(r=>r.id===id)||{name:'',field:'team',value:'',template:'t1',priority:10,scope:'all',schedule:'即时'};modal(id?'编辑标签策略':'新增标签策略',`<form data-form="strategy" data-id="${esc(id||'')}"><div class="form-grid">${inputField('name','策略名称',r.name,'text',true)}<label class="form-field">优先级（数字越小越优先）<input name="priority" type="number" min="1" max="999" value="${r.priority}" required></label><label class="form-field">匹配字段<select name="field">${[['team','责任班组'],['model','设备型号'],['all','所有标签（默认规则）']].map(([v,t])=>`<option value="${v}" ${r.field===v?'selected':''}>${t}</option>`).join('')}</select></label>${inputField('value','等于',r.value)}<label class="form-field">使用模板<select name="template">${templateOptions(r.template)}</select></label><label class="form-field">应用范围<select name="scope"><option value="all">全船已绑定标签</option>${groupOptions(r.scope)}</select></label><label class="form-field full">刷新计划<select name="schedule">${['即时','每天 09:00','每 24 小时'].map(s=>`<option ${r.schedule===s?'selected':''}>${s}</option>`).join('')}</select><small>计划仅保存配置，请用“模拟匹配并创建下发任务”演示执行。</small></label></div>${footerForm()}</form>${id?`<div style="margin-top:15px">${action('strategy-delete','删除策略',id,'link-btn')}</div>`:''}`);}
function directoryForm(id){const d=dir(id)||{name:'',parent:folder};modal(id?'编辑目录':'新建目录',`<form data-form="directory" data-id="${esc(id||'')}"><div class="form-grid">${inputField('name','目录名称',d.name,'text',true)}<label class="form-field">上级目录<select name="parent"><option value="root" ${d.parent==='root'?'selected':''}>${esc(db.ship.name)}（根对象）</option>${db.dirs.filter(x=>depth(x.id)<3&&(!id||!within(x.id,id))).map(x=>`<option value="${x.id}" ${d.parent===x.id?'selected':''}>${esc(path(x.id))}</option>`).join('')}</select></label></div><p class="status-note">最多三级。移动目录时会校验其全部子目录的层级；非空目录不能直接删除。</p>${footerForm()}</form>${id?`<div style="margin-top:15px">${action('directory-delete','删除目录',id,'link-btn')}</div>`:''}`);}
const csvExample='设备编码,设备名称,设备型号,所属部位,责任班组,责任人\nFO-003,备用燃油泵,CB-B40,燃油供给部位,轮机一组,张工\nEL-002,照明配电箱,XL-21,配电间,电气组,陈工';
function importForm(){importRows=[];modal('批量导入资产信息',`<div class="hint">此原型支持 CSV 文件或粘贴 CSV 文本。按设备编码匹配：不存在则新增，已存在则更新。Excel 文件导入后续细化。</div><div class="actions" style="margin-bottom:15px"><label class="btn">选择 CSV 文件<input type="file" accept=".csv,text/csv" id="csv-file" style="display:none"></label>${action('download-import','下载 CSV 模板')}</div><label class="form-field">CSV 内容<textarea id="csv-input" rows="7">${esc(csvExample)}</textarea></label><div class="actions" style="margin-top:15px">${action('import-check','校验并预览','','btn primary')}</div><div id="import-results" aria-live="polite"></div>`,true);}
function parseCSV(s){const rows=[];let row=[],v='',quoted=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(v);v='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&s[i+1]==='\n')i++;row.push(v);if(row.some(x=>x.trim()))rows.push(row);row=[];v='';}else v+=c;}if(quoted)throw Error('CSV 引号未闭合');row.push(v);if(row.some(x=>x.trim()))rows.push(row);return rows;}
function checkImport(){try{const rows=parseCSV($('#csv-input').value.replace(/^\uFEFF/,''));const heads=rows.shift()||[],required=['设备编码','设备名称','所属部位'];if(!required.every(h=>heads.includes(h)))throw Error('缺少必需表头：设备编码、设备名称、所属部位');const keys={设备编码:'code',设备名称:'name',设备型号:'model',所属部位:'dir',责任班组:'team',责任人:'owner'};const seen=new Set();importRows=rows.map((r,i)=>{const obj={};heads.forEach((h,j)=>{if(keys[h])obj[keys[h]]=(r[j]||'').trim();});const matches=db.dirs.filter(d=>d.name===obj.dir||path(d.id)===obj.dir);let error=!obj.code||!obj.name?'编码和名称不能为空':seen.has(obj.code)?'导入文件内设备编码重复':matches.length!==1?'所属部位不存在或名称不唯一':'';seen.add(obj.code);return {...obj,dir:matches[0]?.id,row:i+2,error,existing:db.assets.find(a=>a.code===obj.code)?.id};});if(!importRows.length)throw Error('没有可导入的数据');$('#import-results').innerHTML=`<div class="import-summary">共 ${importRows.length} 条，${importRows.filter(r=>!r.error).length} 条通过，${importRows.filter(r=>r.error).length} 条需要修正。</div><div class="import-preview">${table(['行号','设备编码','设备名称','结果'],importRows.map(r=>`<tr><td>${r.row}</td><td>${esc(r.code)}</td><td>${esc(r.name)}</td><td>${r.error?badge(r.error,'bad'):badge(r.existing?'更新':'新增')}</td></tr>`).join(''))}</div><div class="form-actions"><button class="btn primary" data-action="import-commit" ${importRows.some(r=>r.error)?'disabled':''}>确认导入 ${importRows.length} 条</button></div>`;}catch(e){importRows=[];$('#import-results').innerHTML=`<p class="form-error">${esc(e.message)}</p>`;}}
function download(name,rows){const safe=v=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('已生成 CSV 下载文件');}
function simpleForm(kind,id){let o,title,body;
 if(kind==='gateway'){o=db.gateways.find(g=>g.id===id)||{name:'',dir:'d2',ip:''};title='网关信息';body=inputField('name','网关名称',o.name,'text',true)+inputField('ip','IP 地址',o.ip,'text',true)+`<label class="form-field full">安装目录<select name="dir">${dirOptions(o.dir)}</select></label><p class="status-note">关联 ${db.labels.filter(l=>l.gateway===id).length} 枚标签；网络状态为示例，只读展示。</p>`;}
 if(kind==='user'){o=db.users.find(u=>u.id===id)||{name:'',role:'只读查看',scope:'全船',enabled:true};title='账号与数据权限';body=inputField('name','账号名称',o.name,'text',true)+`<label class="form-field">角色<select name="role">${['系统管理员','资产管理员','标签运维','只读查看'].map(v=>`<option ${o.role===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="form-field">数据范围<select name="scope">${['全船',...db.dirs.filter(d=>d.parent==='root').map(d=>d.name)].map(v=>`<option ${o.scope===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label class="check-row"><input type="checkbox" name="enabled" ${o.enabled?'checked':''}>启用账号</label>`;}
 modal(title,`<form data-form="${kind}" data-id="${esc(id||'')}"><div class="form-grid">${body}</div>${footerForm()}</form>`);}
function guide(){modal('按这条路线体验原型',`<div class="hint">所有操作仅改变本地示例数据。右侧“需求对照”显示产品文档原文，可随时重置演示。</div>${[['01','查看全船概况','了解资产分布、离线标签与待更新事项。','overview'],['02','进入主机舱','选择燃油供给部位，查看或编辑一台设备。','storage'],['03','配置标签内容','编辑模板、调整分组，或导入新的资产数据。','labels/templates'],['04','模拟下发并确认','创建更新任务，点击模拟回执；离线项保留待确认。','labels/tasks'],['05','检查标签状态','查看目标版本与已确认版本，体验恢复在线。','status']].map(([n,t,p,url])=>`<div class="guide-step"><span class="num">${n}</span><div><h3>${t}</h3><p>${p}</p></div>${action('guide-go','前往 →',url)}</div>`).join('')}`);}

document.addEventListener('click',e=>{if(e.target.closest('.nav-link'))document.body.classList.remove('nav-open');const el=e.target.closest('[data-action]');if(!el)return;const {action:a,id}=el.dataset;
 switch(a){
 case 'requirement-demo':openRequirementDemo(id);break;
 case 'mobile-nav':document.body.classList.toggle('nav-open');break;
 case 'toggle-doc':docOpen=!docOpen;reqPanel();break;
 case 'document':modal('产品需求大纲 · v0.1',`<article class="document-content">${DOC.document}</article>`,true);break;
 case 'guide':guide();break;
 case 'guide-go':closeModal();if(id==='storage')folder='d3';go(...id.split('/'));break;
 case 'close-dialog':closeModal();break;
 case 'reset':modal('重置本地演示数据',`<p>将恢复最初的示例资产、标签、模板和任务，清除你在此原型中的修改。</p><div class="form-actions">${action('close-dialog','取消')}${action('reset-confirm','确认重置','','btn danger')}</div>`);break;
 case 'reset-confirm':db=seed();persist();closeModal();folder='root';selected.clear();query='';filter='all';groupFilter='';render();toast('已恢复初始演示数据');break;
 case 'stat-nav':if(id==='tasks')go('labels','tasks');else go(id);break;
 case 'folder':folder=id;query='';render();break;
 case 'open-folder':folder=id;go('storage');break;
 case 'directory-add':if(depth(folder)>=3){toast('当前已是三级目录，请选择上级目录后新增');break;}directoryForm();break;
 case 'directory-edit':directoryForm(id);break;
 case 'directory-delete':if(db.dirs.some(d=>d.parent===id)||assetsIn(id).length){toast('目录仍有下级目录或资产，请先迁移后再删除');break;}db.dirs=db.dirs.filter(d=>d.id!==id);folder='root';log('删除目录',id);closeModal();render();toast('目录已删除');break;
 case 'asset-detail':assetDetail(id);break;
 case 'asset-add':assetForm();break;
 case 'asset-edit':assetForm(id);break;
 case 'asset-move':modal('调整资产归属',`<form data-form="move" data-id="${id}"><p class="status-note">${esc(asset(id).name)} · 关联标签随资产同步调整归属。</p><label class="form-field">目标目录<select name="dir">${dirOptions(asset(id).dir)}</select></label>${footerForm('确认迁移')}</form>`);break;
 case 'bind':bindForm(id);break;
 case 'bind-label':bindForm('',id);break;
 case 'label-detail':labelDetail(id);break;
 case 'label-add':modal('登记电子标签',`<form data-form="label"><div class="form-grid">${inputField('mac','MAC 地址','C8:29:01:00:00:10','text',true)}<label class="form-field">型号<input value="STag29AQ · 2.9 英寸" readonly></label><label class="form-field full">关联网关<select name="gateway">${db.gateways.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></label></div>${footerForm('登记标签')}</form>`);break;
 case 'simulate-online':{const l=label(id);l.online=!l.online;l.last=stamp();log('模拟通信状态',l.mac+' '+(l.online?'恢复在线':'离线'));render();labelDetail(id);toast('已模拟'+(l.online?'恢复在线，可到任务中确认回执':'离线'));break;}
 case 'toggle-paused':{const l=label(id);l.state=l.state==='paused'?'active':'paused';log('标签启停',l.mac+' '+stateText(l));render();labelDetail(id);break;}
 case 'led':log('模拟点灯',label(id).mac+' · 绿色闪烁示例');toast('已模拟点灯指令；未连接现场 LED');break;
 case 'unbind':modal('解除资产绑定',`<p>解除 ${esc(label(id).mac)} 与 ${esc(labelName(label(id)))} 的绑定。资产与标签记录均保留。</p><div class="form-actions">${action('close-dialog','取消')}${action('unbind-confirm','确认解绑',id,'btn danger')}</div>`);break;
 case 'unbind-confirm':{const l=label(id);l.asset=null;l.published=0;l.version++;log('解除绑定',l.mac);render();labelDetail(id);toast('已解除绑定，现场清屏不在此模拟操作内');break;}
 case 'publish-one':publishForm([id]);break;
 case 'publish-selected':publishForm([...selected]);break;
 case 'publish-all':publishForm();break;
 case 'clear-selection':selected.clear();render();break;
 case 'group-selected':modal('将选中标签加入分组',`<form data-form="group-selected"><label class="form-field">目标分组<select name="group" required>${groupOptions('')}</select></label><p class="status-note">共 ${selected.size} 枚标签，将追加到选定分组。</p>${footerForm()}</form>`);break;
 case 'group-edit':groupForm(id);break;
 case 'group-open':pendingNav={groupFilter:id};go('labels','devices');break;
 case 'group-publish':publishForm(db.groups.find(g=>g.id===id).members.length?db.groups.find(g=>g.id===id).members:['no-label']);break;
 case 'group-delete':db.groups=db.groups.filter(g=>g.id!==id);log('删除分组',id);closeModal();render();break;
 case 'template-edit':templateForm(id);break;
 case 'template-copy':{const t=tpl(id),n={...t,id:uid('t'),name:t.name+' 副本',revision:1};db.templates.push(n);log('复制模板',n.name);render();toast('模板已复制');break;}
 case 'template-apply':modal('应用模板到标签',`<form data-form="template-apply" data-id="${id}"><p class="status-note">${esc(tpl(id).name)} · 应用后标记为待更新，尚未下发。</p><div class="check-list">${db.labels.filter(l=>l.asset).map(l=>`<label class="check-row"><input type="checkbox" name="labels" value="${l.id}"><span>${esc(labelName(l))}</span><small>${esc(l.mac.slice(-8))}</small></label>`).join('')}</div>${footerForm('应用模板')}</form>`);break;
 case 'task-detail':taskDetail(id);break;
 case 'task-receipt':{const t=db.tasks.find(t=>t.id===id);let n=0;t.items.forEach(i=>{const l=label(i.label);if(i.status==='waiting'&&l.online&&l.state!=='paused'&&l.asset){i.status='success';l.published=Math.max(l.published,i.version);n++;}});log('模拟回执',t.name+' · '+n+' 枚确认更新');render();taskDetail(id);toast(n?`已模拟 ${n} 枚标签的成功回执`:'没有可确认的标签；请检查在线状态或先重试失败项');break;}
 case 'task-retry':{const t=db.tasks.find(t=>t.id===id);let n=0;t.items.forEach(i=>{if(i.status==='failed'){i.status='waiting';i.version=label(i.label).version;n++;}});log('重试失败项',t.name+' · '+n+' 枚');render();taskDetail(id);toast(n?'失败项已重新提交，可模拟回执':'当前任务没有失败项');break;}
 case 'strategy-edit':strategyForm(id);break;
 case 'strategy-toggle':{const r=db.strategies.find(r=>r.id===id);r.enabled=!r.enabled;log('策略启停',r.name);render();break;}
 case 'strategy-delete':db.strategies=db.strategies.filter(r=>r.id!==id);log('删除策略',id);closeModal();render();break;
 case 'strategy-run':{const rules=[...db.strategies].filter(r=>r.enabled).sort((a,b)=>a.priority-b.priority),ids=[];db.labels.filter(l=>l.asset&&l.state!=='paused').forEach(l=>{const a=asset(l.asset);const r=rules.find(r=>(r.scope==='all'||db.groups.find(g=>g.id===r.scope)?.members.includes(l.id))&&(r.field==='all'||a[r.field]===r.value));if(r){if(l.template!==r.template){l.template=r.template;l.version++;}ids.push(l.id);}});const t=newTask(ids,'策略匹配更新（手动模拟）');if(t){render();taskDetail(t.id);toast(`匹配 ${ids.length} 枚标签，已创建模拟任务`);}else toast('没有匹配到可下发标签');break;}
 case 'status-filter':filter=id;selected.clear();render();break;
 case 'refresh-status':toast('已重新读取本地示例状态，未请求现场硬件');render();break;
 case 'field-add':case 'field-edit':{const f=db.fields.find(f=>f.id===id)||{name:'',type:'文本',required:false};const locked=['code','name','dir'].includes(id);modal(id?'字段配置':'添加自定义字段',`<form data-form="field" data-id="${esc(id||'')}"><div class="form-grid">${inputField('name','字段名称',f.name,'text',true)}<label class="form-field">字段类型<select name="type" ${id?'disabled':''}>${[...new Set([f.type,'文本','数字'])].map(t=>`<option ${f.type===t?'selected':''}>${t}</option>`).join('')}</select><small>${id?'现有字段类型固定，避免改变已保存数据语义。':''}</small></label><label class="check-row"><input name="required" type="checkbox" ${f.required?'checked':''} ${locked?'disabled':''}>必填字段</label></div>${footerForm()}</form>`);break;}
 case 'import':importForm();break;
 case 'import-check':checkImport();break;
 case 'import-commit':{if(!importRows.length||importRows.some(r=>r.error))return;const input=$('#csv-input').value;const n=importRows.length;importRows.forEach(r=>{const a=r.existing?asset(r.existing):{id:uid('a')};['code','name','model','dir','team','owner'].forEach(k=>a[k]=r[k]||'');if(!r.existing)db.assets.push(a);const l=labelFor(a);if(l)l.version++;});log('批量导入',n+' 条资产数据');importRows=[];closeModal();render();toast(`已导入 ${n} 条资产数据`);break;}
 case 'download-import':download('船舶资产导入模板.csv',parseCSV(csvExample));break;
 case 'export-assets':{const items=(route.page==='storage'?assetsIn(folder):db.assets).filter(a=>[a.name,a.code,a.team].join(' ').includes(query));download('船舶资产数据.csv',[['设备编码','设备名称','设备型号','所属部位','责任班组','责任人'],...items.map(a=>[a.code,a.name,a.model,path(a.dir),a.team,a.owner])]);break;}
 case 'export-labels':download('电子标签状态.csv',[['MAC','关联设备','在线状态','电量','RSSI','最后上报'],...filteredLabels().map(l=>[l.mac,labelName(l),l.online?'在线':'离线',l.battery,l.rssi,l.last])]);break;
 case 'gateway-edit':simpleForm('gateway',id);break;
 case 'user-edit':simpleForm('user',id);break;
 }
});
document.addEventListener('submit',e=>{const f=e.target.closest('form[data-form]');if(!f)return;e.preventDefault();const data=new FormData(f),v=Object.fromEntries(data),id=f.dataset.id,kind=f.dataset.form;let err='';const fail=s=>{const el=f.querySelector('#form-error');if(el)el.textContent=s;else toast(s);};
 if(kind==='asset'){if(db.assets.some(a=>a.code===v.code.trim()&&a.id!==id))return fail('设备编码已存在，请使用唯一编码');const a=asset(id)||{id:uid('a')};db.fields.filter(f=>f.id!=='dir').forEach(field=>a[field.id]=(v[field.id]||'').trim());a.dir=v.dir;if(!id)db.assets.push(a);const l=labelFor(a);if(l)l.version++;log(id?'编辑资产':'新增资产',a.name);}
 if(kind==='move'){const a=asset(id);a.dir=v.dir;const l=labelFor(a);if(l)l.version++;log('资产迁移',a.name+' → '+path(v.dir));}
 if(kind==='directory'){const d=dir(id),subDepth=id?Math.max(0,...db.dirs.filter(x=>within(x.id,id)).map(x=>depth(x.id)-depth(id))):0;if(depth(v.parent)+1+subDepth>3)return fail('移动后会超过三级目录限制');if(db.dirs.some(x=>x.parent===v.parent&&x.name===v.name.trim()&&x.id!==id))return fail('同级目录名称不可重复');if(d){d.name=v.name.trim();d.parent=v.parent;}else db.dirs.push({id:uid('d'),name:v.name.trim(),parent:v.parent});log('维护目录',v.name);}
 if(kind==='label'){if(!/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/i.test(v.mac))return fail('请输入正确的 MAC 地址，如 C8:29:01:00:00:10');if(db.labels.some(l=>l.mac===v.mac.toUpperCase()))return fail('此 MAC 已登记');db.labels.push({id:uid('l'),mac:v.mac.toUpperCase(),asset:null,online:true,battery:100,rssi:-55,template:'t1',version:1,published:0,gateway:v.gateway,last:stamp(),state:'active'});log('登记标签',v.mac);}
 if(kind==='bind'){const l=label(v.label);if(!l)return fail('请选择可用标签');if(l.state==='paused')return fail('标签已停用，请先在详情中启用');const old=labelFor(asset(v.asset));if(old&&old.id!==l.id){old.asset=null;old.version++;old.published=0;}l.asset=v.asset;l.version++;l.published=0;log('绑定资产',labelName(l)+' ↔ '+l.mac);closeModal();render();labelDetail(l.id);toast('已绑定，等待首次下发');return;}
 if(kind==='publish'){const ids=data.getAll('labels');if(!ids.length)return fail('至少选择一枚已绑定且启用的标签');const t=newTask(ids,v.name.trim());closeModal();selected.clear();go('labels','tasks');setTimeout(()=>taskDetail(t.id),0);toast('已创建模拟任务，等待回执');return;}
 if(kind==='group'){const name=v.name.trim();if(db.groups.some(g=>g.name===name&&g.id!==id))return fail('分组名称已存在');const g=db.groups.find(g=>g.id===id)||{id:uid('gr')};Object.assign(g,{name,description:v.description.trim(),members:data.getAll('members')});if(!id)db.groups.push(g);log('维护分组',name);}
 if(kind==='group-selected'){const g=db.groups.find(g=>g.id===v.group);if(!g)return fail('请先创建一个分组');g.members=[...new Set([...g.members,...selected])];log('加入分组',g.name+' · '+selected.size+' 枚标签');selected.clear();}
 if(kind==='template'){const t=tpl(id)||{id:uid('t'),revision:0};Object.assign(t,{name:v.name.trim(),heading:v.heading.trim(),color:v.color,showModel:data.has('showModel'),showOwner:data.has('showOwner'),revision:t.revision+1});if(!id)db.templates.push(t);db.labels.filter(l=>l.template===t.id).forEach(l=>l.version++);log('保存模板',t.name+' v'+t.revision);}
 if(kind==='template-apply'){const ids=data.getAll('labels');if(!ids.length)return fail('至少选择一枚标签');ids.forEach(id2=>{const l=label(id2);l.template=id;l.version++;});log('应用模板',tpl(id).name+' · '+ids.length+' 枚标签');}
 if(kind==='strategy'){if(v.field!=='all'&&!v.value.trim())return fail('请填写匹配值');const r=db.strategies.find(r=>r.id===id)||{id:uid('r'),enabled:true};Object.assign(r,{name:v.name.trim(),field:v.field,value:v.value.trim(),template:v.template,priority:Number(v.priority),scope:v.scope,schedule:v.schedule});if(!id)db.strategies.push(r);log('维护标签策略',r.name);}
 if(kind==='field'){if(db.fields.some(x=>x.name===v.name.trim()&&x.id!==id))return fail('字段名称已存在');const field=db.fields.find(x=>x.id===id);if(field){field.name=v.name.trim();if(!['code','name','dir'].includes(id))field.required=data.has('required');}else db.fields.push({id:uid('field'),name:v.name.trim(),type:v.type,required:data.has('required')});log('字段配置',v.name);}
 if(kind==='gateway'){if(!/^(\d{1,3}\.){3}\d{1,3}$/.test(v.ip)||v.ip.split('.').some(x=>+x>255))return fail('请输入有效的 IPv4 地址');const g=db.gateways.find(g=>g.id===id)||{id:uid('g'),online:true};Object.assign(g,{name:v.name.trim(),ip:v.ip,dir:v.dir});if(!id)db.gateways.push(g);log('维护网关',g.name);}
 if(kind==='user'){const u=db.users.find(u=>u.id===id)||{id:uid('u')};Object.assign(u,{name:v.name.trim(),role:v.role,scope:v.scope,enabled:data.has('enabled')});if(!id)db.users.push(u);log('维护账号权限',u.name+' · '+u.role);}
 if(kind==='settings'){db.ship={name:v.shipName.trim(),code:v.shipCode.trim()};for(const k of ['low','weak','offline','refresh'])db.settings[k]=Number(v[k]);log('修改基础设置','船舶信息与异常阈值');render();toast('设置已保存');return;}
 closeModal();render();toast('已保存到本地演示数据');
});
document.addEventListener('change',async e=>{const t=e.target;if(t.matches('[data-filter]')){filter=t.value;selected.clear();render();}if(t.matches('[data-group-filter]')){groupFilter=t.value;selected.clear();render();}if(t.matches('[data-select]')){t.checked?selected.add(t.dataset.select):selected.delete(t.dataset.select);render();}if(t.matches('[data-select-all]')){filteredLabels().forEach(l=>t.checked?selected.add(l.id):selected.delete(l.id));render();}if(t.id==='csv-file'&&t.files[0]){if(t.files[0].size>1024*1024){toast('演示文件请控制在 1 MB 内');return;}$('#csv-input').value=await t.files[0].text();checkImport();}});
document.addEventListener('input',e=>{if(e.isComposing)return;const t=e.target;if(t.matches('[data-search]')){query=t.value;const pos=t.selectionStart;selected.clear();render();const input=$('[data-search]');input.focus();input.setSelectionRange(pos,pos);}if(t.closest('[data-form="template"]')&&t.matches('[data-preview]')){const f=t.closest('form'),d=new FormData(f);$('#live-preview').innerHTML=preview({heading:d.get('heading'),color:d.get('color'),showModel:d.has('showModel'),showOwner:d.has('showOwner')},asset(d.get('previewAsset')));}if(t.id==='csv-input'){importRows=[];$('#import-results').innerHTML='';}});
document.addEventListener('keydown',e=>{const t=e.target.closest('.stat[role=button]');if(t&&(e.key==='Enter'||e.key===' ')){e.preventDefault();t.click();}});
window.addEventListener('hashchange',readRoute);
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
readRoute();persist();
